#!/bin/sh
FORTH=${FORTH:-.././64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done

out=$(echo 0 digit 9 digit 10 digit 11 digit . . . . | $FORTH | sed 's/ *$//')
echo $out
case $out in
    ("66 65 57 48") exit 0;;
esac
exit 2
