#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '123 0 <# # OVER . # OVER . # OVER .')
printf "%s\n" "$out"
case $out in
    ('12 1 0 ') exit 0;;
esac
exit 2
