#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '5 7 9 <# #> . drop .' | $FORTH)
printf "%s\n" "$out"
case $out in
    ('0 5 ') exit 0;;
esac
exit 2
