#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '137 0 <# # # #> type' | $FORTH)
printf "%s\n" "$out"
case $out in
    ('37') exit 0;;
esac
exit 2
