#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '137 0 <# # # #> TYPE')
printf "%s\n" "$out"
case $out in
    ('37') exit 0;;
esac
exit 2
