#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '-1 -1 <# # # # 45 HOLD #S #> TYPE')
printf "%s\n" "$out"
case $out in
    ('340282366920938463463374607431768211-455') exit 0;;
esac
exit 2
