#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '-1 -1 <# # # # 45 hold #s #> type' | $FORTH)
printf "%s\n" "$out"
case $out in
    ('340282366920938463463374607431768211-455') exit 0;;
esac
exit 2
