#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
: seven 7 ;
5 '\'' seven execute
. .')
printf "%s\n" "$out"
case $out in
    ('7 5 ') exit 0;;
esac
exit 2
