#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': s ( drop drop drop ) ( ) 7 ( ) ;
  9 s . .')
printf "%s\n" "$out"
case "$out" in
    ("7 9 ") exit 0;;
esac
exit 2
