#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
# Check that () is a valid token.
out=$($FORTH -c ': () 7 ( 9 ) ;
  5 () . .')
printf "%s\n" "$out"
case "$out" in
    ("7 5 ") exit 0;;
esac
exit 2
