#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '111111111 DUP DUP * .
DUP NEGATE DUP * .
DUP DUP NEGATE * .
DUP NEGATE SWAP * .
')
printf "%s\n" "$out"
case "$out" in
    ("12345678987654321 12345678987654321 -12345678987654321 -12345678987654321 ") exit 0;;
esac
exit 2
