#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
# Create a product that is largest unsigned single.
out=$($FORTH -c '65535 65537 *
dup 2 +
*
0 D.')
printf "%s\n" "$out"
case "$out" in
    ("18446744073709551615 ") exit 0;;
esac
exit 2
