#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '6 254 10 */ .')
printf "%s\n" "$out"
case "$out" in
    ("152 ") exit 0;;
esac
exit 2
