#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
# Test that `*` works for unsigned values outside the signed range
out=$($FORTH -c '4000000000 dup * U.
  -1 1 * U.
  -1 0 * U.
')
printf "%s\n" "$out"
case "$out" in
    ("16000000000000000000 18446744073709551615 0 ") exit 0;;
esac
exit 2
