#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '1 -7 -0 9 . . . .' | $FORTH)
echo $out
case "$out" in
    ("9 0 -7 1 ") exit 0;;
esac
exit 2
