#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '1 negate 0< negate . 77 0< .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("1 0 ") exit 0;;
esac
exit 2
