#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '-1 0= 222222222222222222 0= 0 0= 8 0= 0= . . . .')
printf "%s\n" "$out"
case "$out" in
    ("-1 -1 0 0 ") exit 0;;
esac
exit 2
