#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c "$(printf "1 2 3\n. . .\n")")
printf "%s\n" "$out"
case "$out" in
    ("3 2 1 ") exit 0;;
esac
exit 2
