#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c 'HERE
9876543210
-123456789
HERE
2 cells ALLOT
2!
DUP @ .
cell+ @ .
')
printf "%s\n" "$out"
case "$out" in
    ("-123456789 9876543210 ") exit 0;;
esac
exit 2
