#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
9876543210
-123456789
-1
HERE
3 cells ALLOT
TUCK !
TUCK cell+ !
TUCK cell+ cell+ !
2@
. .
DEPTH .
')
printf "%s\n" "$out"
case "$out" in
    ("-1 -123456789 0 ") exit 0;;
esac
exit 2
