#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '
9876543210
-123456789
-1
here
3 cells allot
tuck !
tuck cell+ !
tuck cell+ cell+ !
2@
. .
depth .
' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("-1 -123456789 0 ") exit 0;;
esac
exit 2
