#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '7 5 6 2dup . . . . .')
printf "%s\n" "$out"
case "$out" in
    ("6 5 6 5 7 ") exit 0;;
esac
exit 2
