#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '1 2 3 4 5 2OVER
. . . . . . .')
printf "%s\n" "$out"
case "$out" in
    ("3 2 5 4 3 2 1 ") exit 0;;
esac
exit 2
