#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '1 2 3
: t >R >R 2R@ R> R> ;
t . . . . .
')
printf "%s\n" "$out"
case "$out" in
    ("3 2 2 3 1 ") exit 0;;
esac
exit 2
