#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '7 8 9 10 11 12 2rot . . . . . .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("8 7 12 11 10 9 ") exit 0;;
esac
exit 2
