#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo 3 4 + . | $FORTH | sed 's/ *$//')
printf "%s\n" "$out"
case $out in
    (7) exit 0;;
esac
exit 2
