#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': trip DUP DUP ; 7 trip . . .')
printf "%s\n" "$out"
case "$out" in
    ("7 7 7 ") exit 0;;
esac
exit 2
