#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': two 2 ; two two + .')
printf "%s\n" "$out"
case "$out" in
    ("4 ") exit 0;;
esac
exit 2
