#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '1 9 < negate 9 9 < negate 10 9 < negate . . .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("0 0 1 ") exit 0;;
esac
exit 2
