#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '0 -1 > . 0 0 > . -1 -2 > . 1 0 > .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("-1 0 -1 -1 ") exit 0;;
esac
exit 2
