#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c "CREATE magic  magic  ' magic >BODY  NEGATE + .")
printf "%s\n" "$out"
case $out in
    ("0 ") exit 0;;
esac
exit 2
