#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo create magic magic \' magic \>body negate + . | $FORTH | sed 's/ *$//')
printf "%s\n" "$out"
case $out in
    (0) exit 0;;
esac
exit 2
