#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '>IN @ NEGATE >IN @ + .')
printf "%s\n" "$out"
case $out in
    ("13 ") exit 0;;
esac
exit 2
