#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '>in @ negate >in @ + .' | $FORTH | sed 's/ *$//')
printf "%s\n" "$out"
case $out in
    (13) exit 0;;
esac
exit 2
