#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x S" 3@5" ;
0 0 x >NUMBER
. DROP D.')
printf '%s\n' "$out"
case "$out" in
    ("2 3 ") exit 0;;
    esac
exit 2
