#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x parse-word FALSE FALSE 2SWAP >number ;
x 37.59 DROP DROP DROP .')
printf '%s\n' "$out"
case "$out" in
    ("37 ") exit 0;;
    esac
exit 2
