#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(printf "1 ?dup 0 ?dup\n. . .\n" | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("0 1 1 ") exit 0;;
esac
exit 2
