#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
: x [ 2 2 * ] LITERAL ;
DEPTH .
x .
DEPTH .')
printf "%s\n" "$out"
case "$out" in
    ("0 4 0 ") exit 0;;
esac
exit 2
