#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': cc [CHAR] A [CHAR] B ;
cc cc . . . .')
printf "%s\n" "$out"
case "$out" in
    ("66 65 66 65 ") exit 0;;
esac
exit 2
