#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x [COMPILE] LITERAL ;
: y x ; IMMEDIATE
3 99 : z y ; .
z .')
printf "%s\n" "$out"
case "$out" in
    ("3 99 ") exit 0;;
esac
exit 2
