#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo ': x [compile] literal ;
: y x ; immediate
3 99 : z y ; .
z .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("3 99 ") exit 0;;
esac
exit 2
