#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x ABORT" I am abort" ;
: y ABORT" I am test fail" ;
0 y
1 x')
printf "%s\n" "$out"
case "$out" in
    ("I am abort") exit 0;;
esac
exit 2
