#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo 7 negate abs 3 abs . . | $FORTH)
printf "%s\n" "$out"
case $out in
    ('3 7 ') exit 0;;
esac
exit 2
