#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '0 ABS  7 NEGATE ABS  3 ABS  . . .')
printf "%s\n" "$out"
case $out in
    ('3 7 0 ') exit 0;;
esac
exit 2
