#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
0 ALIGNED
1 ALIGNED
2 ALIGNED
3 ALIGNED
5 ALIGNED
8 ALIGNED
13 ALIGNED
. . . . . . .
')
printf "%s\n" "$out"
case "$out" in
    ("16 8 8 8 8 8 0 ") exit 0;;
esac
exit 2
