#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done

out=$($FORTH -c '
ALIGN here
1 allot ALIGN here
- .
')
printf "%s\n" "$out"
case "$out" in
    ("-8 ") exit 0;;
esac
exit 2
