#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
0 aligned
1 aligned
2 aligned
3 aligned
5 aligned
8 aligned
13 aligned
. . . . . . .
')
printf "%s\n" "$out"
case "$out" in
    ("16 8 8 8 8 8 0 ") exit 0;;
esac
exit 2
