#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '129 7 and . 7 129 or .')
printf "%s\n" "$out"
case "$out" in
    ("1 135 ") exit 0;;
esac
exit 2
