#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '8 9 10 11 12 25 16 BASE ! . . . . . .')
printf "%s\n" "$out"
case "$out" in
    ("19 C B A 9 8 ") exit 0;;
esac
exit 2
