#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '97 0 <# # BL HOLD # #> TYPE')
printf "%s\n" "$out"
case "$out" in
    ("9 7") exit 0;;
esac
exit 2
