#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo ': c parse-word drop c@ ; c 0a .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("48 ") exit 0;;
esac
exit 2
