#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c 'char A char . . .')
printf "%s\n" "$out"
case "$out" in
    ("46 65 ") exit 0;;
esac
exit 2
