#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c 'VARIABLE v
: c S" abcdefgh" ;
c v SWAP 
CMOVE>
v 8 TYPE
v 2 +
v 1 +
5 CMOVE>
v 8 TYPE' )
printf "%s\n" "$out"
case $out in
    (abcdefghaggggggh) exit 0;;
esac
exit 2
