#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': a S" aa" ;  : b S" bb" ;
a b COMPARE .
a a COMPARE .
b a COMPARE .

a DROP 0 a COMPARE .
a DROP 0 b DROP 0 COMPARE .
a a DROP 0 COMPARE .
')
printf "%s\n" "$out"
case "$out" in
    ("-1 0 1 -1 0 1 ") exit 0;;
esac
exit 2
