#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': a s" aa" ;  : b s" bb" ;
a b COMPARE .
a a COMPARE .
b a COMPARE .

a drop 0 a COMPARE .
a drop 0 b drop 0 COMPARE .
a a drop 0 COMPARE .
')
printf "%s\n" "$out"
case "$out" in
    ("-1 0 1 -1 0 1 ") exit 0;;
esac
exit 2
