#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
3 CONSTANT pi
: foo pi s" foo " TYPE ;
foo .
')
printf "%s\n" "$out"
case "$out" in
    ("foo 3 ") exit 0;;
esac
exit 2
