#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '7 0 -3 0 D+ . .')
printf "%s\n" "$out"
case "$out" in
    ("1 4 ") exit 0;;
esac
exit 2
