#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '7 0 -3 d+- . .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("-1 -7 ") exit 0;;
esac
exit 2
