#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '-1 0 D0=
0 0 D0= . .')
printf "%s\n" "$out"
case "$out" in
    ("-1 0 ") exit 0;;
esac
exit 2
