#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(printf "9 depth\n. .\n" | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("1 9 ") exit 0;;
esac
exit 2
