#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '7 2 DNEGATE . .
-9 -1 DNEGATE D.
2 0 DNEGATE D.')
printf "%s\n" "$out"
case $out in
    ('-3 -7 9 -2 ') exit 0;;
esac
exit 2
