#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c "
: x 0 DO 64 emit 3 0 DO 47 emit LOOP LOOP ; 2 x"
)
printf "%s\n" "$out"
case "$out" in
    ("@///@///") exit 0;;
esac
exit 2
