#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x DOES> INVERT ;
create foo
foo
x
foo
+ .')
printf "%s\n" "$out"
case "$out" in
    ("-1 ") exit 0;;
esac
exit 2
