#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo ': x does> invert ;
create foo
foo
x
foo
+ .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("-1 ") exit 0;;
esac
exit 2
