#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ' 7 negate 99 . .')
printf "%s\n" "$out"
case $out in
    ('99 -7 ') exit 0;;
esac
exit 2
