#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '13 : x .( hello) 7 ; . x x + .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("hello13 14 ") exit 0;;
esac
exit 2
