#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x .( ) 7 ; x .')
printf "%s\n" "$out"
case "$out" in
    ("7 ") exit 0;;
esac
exit 2
