#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
# Assumes ASCII
out=$($FORTH -c ': p s" foo" ; p DUMP
')
printf "%s\n" "$out"
case "$out" in
    ("66 6F 6F ") exit 0;;
esac
exit 2
