#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '1 DUP 3 . . .')
printf "%s\n" "$out"
case "$out" in
    ("3 1 1 ") exit 0;;
esac
exit 2
