#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo ': p if 7 else 9 then ;
  0 p .
  1 p .
  -1 p .
  ' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("9 7 7 ") exit 0;;
esac
exit 2
