#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': p IF 7 ELSE 9 THEN ;
  0 p .
  1 p .
  -1 p .
  ')
printf "%s\n" "$out"
case "$out" in
    ("9 7 7 ") exit 0;;
esac
exit 2
