#!/bin/sh
FORTH=${FORTH:-../64th}
# Test that PARSE-WORD (used by VARIABLE) works
# when token is not terminated by a blank but
# is terminated by end of record.
out=$(echo 'variable bop
97 bop !
3 bop @ . .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("97 3 ") exit 0;;
esac
exit 2
