#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo ': x s" hello" ;
  x evaluate' | $FORTH)
printf '%s\n' "$out"
if [ "${#out}" -lt 9 ]
then
    exit 0
fi
exit 2
