#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo ': x s" 2 * 1+" ;
  7 9 x evaluate . .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("19 7 ") exit 0;;
esac
exit 2
