#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
here
16 allot
DUP 16 99 fill
DUP 12 33 fill
DUP C@ .
DUP 11 + C@ .
DUP 12 + C@ .
DUP 15 + C@ .
')
printf "%s\n" "$out"
case "$out" in
    ("33 33 99 99 ") exit 0;;
esac
exit 2
