#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
 4 S>D  3 FM/MOD . .
-4 S>D  3 FM/MOD . .
 4 S>D -3 FM/MOD . .
-4 S>D -3 FM/MOD . .')
printf "%s\n" "$out"
case $out in
    ('1 1 -2 2 -2 -2 1 -1 ') exit 0;;
esac
exit 2
