#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
: sf S" foo" ;
sf GET-CURRENT SEARCH-WORDLIST .
: ss S" STATE" ;
ss GET-CURRENT SEARCH-WORDLIST 0= .
')
printf "%s\n" "$out"
case "$out" in
    ("0 0 ") exit 0;;
esac
exit 2
