#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo here 808 , @ . | $FORTH | sed 's/ *$//')
printf "%s\n" "$out"
case $out in
    (808) exit 0;;
esac
exit 2
