#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '13799 0 <# # # # 44 hold #s #> type' | $FORTH)
printf "%s\n" "$out"
case $out in
    ('13,799') exit 0;;
esac
exit 2
