#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '
: s do i . loop ;
2 -1 s
' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("-1 0 1 ") exit 0;;
esac
exit 2
