#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': select IF SWAP THEN DROP ;
  1 2 3 select .
  8 9 0 select .
  DEPTH .')
printf "%s\n" "$out"
case "$out" in
    ("2 8 0 ") exit 0;;
esac
exit 2
