#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo ': seven 7 ; immediate
      : dummy seven ;
      .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("7 ") exit 0;;
esac
exit 2
