#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '-555 INVERT .')
printf "%s\n" "$out"
case "$out" in
    ("554 ") exit 0;;
esac
exit 2
