#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
: s 0 DO  DUP 0  DO  I . J . BL emit  LOOP  LOOP ;
3 2 s
DEPTH .
')
printf "%s\n" "$out"
case "$out" in
    ("0 0  1 0  2 0  0 1  1 1  2 1  1 ") exit 0;;
esac
exit 2
