#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '10 0 10 1 M*/ . .')
printf "%s\n" "$out"
case "$out" in
    ("0 100 ") exit 0;;
esac
exit 2
