#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo 7 2 negate 1 negate + + . | $FORTH | sed 's/ *$//')
printf "%s\n" "$out"
case $out in
    (4) exit 0;;
esac
exit 2
