#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '7 46 parse drop drop. . c@ . .' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("9 100 7 ") exit 0;;
esac
exit 2
