#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '64 PARSE foo@ DUP . TYPE')
printf "%s\n" "$out"
case "$out" in
    ("3 foo") exit 0;;
esac
exit 2
