#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '64 parse foo@ dup . type' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("3 foo") exit 0;;
esac
exit 2
