#!/bin/sh
FORTH=${FORTH:-../64th}
# Test bug when PARSE-WORD is used before buffer input end.
out=$(echo 'depth . parse-word
  depth .' | $FORTH)
echo $out
case "$out" in
    ("0 2 ") exit 0;;
esac
exit 2
