#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
  : Endif POSTPONE THEN ; IMMEDIATE
  DEPTH .
  : x IF 1+ Endif . ;
  DEPTH .
  1 0 x
  2 1 x
  DEPTH . 9 .
  : y POSTPONE TRUE ; IMMEDIATE
  DEPTH .
  : z y ;
  DEPTH .
  z .
  DEPTH . 9 .
')
printf "%s\n" "$out"
case "$out" in
    ("0 0 1 3 0 9 0 0 -1 0 9 ") exit 0;;
esac
exit 2
