#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': Endif POSTPONE THEN ; IMMEDIATE
  : x IF 1+ Endif . ;
  1 0 x
  2 1 x
')
printf "%s\n" "$out"
case "$out" in
    ("1 3 ") exit 0;;
esac
exit 2
