#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c 'source TYPE')
printf "%s\n" "$out"
case "$out" in
    ("source TYPE") exit 0;;
esac
exit 2
