#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': dub >R R@ R> ; 99 dub . . ')
printf "%s\n" "$out"
case "$out" in
    ("99 99 ") exit 0;;
esac
exit 2
