#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$( $FORTH -c '1 97 3 rot . 5 rot . . .' )
printf "%s\n" "$out"
case "$out" in
    ("1 97 5 3 ") exit 0;;
esac
exit 2
