#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo ': x s" I like Dog Food" ; x type' | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("I like Dog Food") exit 0;;
esac
exit 2
