#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x s" I like Dog Food" ; x type')
printf "%s\n" "$out"
case "$out" in
    ("I like Dog Food") exit 0;;
esac
exit 2
