#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
# test zero length string (suggested by std1994 A.6.2.2008)
out=$($FORTH -c ': x S" " ; x . DEPTH .')
printf "%s\n" "$out"
case "$out" in
    ("0 1 ") exit 0;;
esac
exit 2
