#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '1 S>D D. -97 S>D D.')
printf "%s\n" "$out"
case "$out" in
    ("1 -97 ") exit 0;;
esac
exit 2
