#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '1 s>d d. -97 s>d d.')
printf "%s\n" "$out"
case "$out" in
    ("1 -97 ") exit 0;;
esac
exit 2
