#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
: bar S" bar" ;
: f S" foo" ;
WORDLIST DUP SET-CURRENT
: foo S" foo" ;
f findword . 9 .
bar findword . 0= .
f ROT SEARCH-WORDLIST . 0= .
9 . DEPTH .
')
printf "%s\n" "$out"
case "$out" in
    ("0 9 -1 0 -1 0 9 0 ") exit 0;;
esac
exit 2
