#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '123 0 <# #s 123 negate sign #> type' | $FORTH)
printf "%s\n" "$out"
case $out in
    ('-123') exit 0;;
esac
exit 2
