#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
4 3 /MOD . .
-4 -3 /MOD . .
-9223372036854775808 1 /MOD . .
')

printf "%s\n" "$out"
case $out in
    ("1 1 1 -1 -9223372036854775808 0 ") exit 0;;
esac
exit 2
