#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(printf "1 2 swap 3\n. . .\n" | $FORTH)
printf "%s\n" "$out"
case "$out" in
    ("3 1 2 ") exit 0;;
esac
exit 2
