#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
9 VALUE doob
doob .
99 TO doob
doob .
: zero 0 TO doob ;
doob .
zero
doob .
DEPTH .
')
printf "%s\n" "$out"
case $out in
    ('9 99 99 0 0 ') exit 0;;
esac
exit 2
