#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c 'TRUE invert .
TRUE TRUE xor .
TRUE .
TRUE FALSE = .
')
printf "%s\n" "$out"
case "$out" in
    ("0 0 -1 0 ") exit 0;;
esac
exit 2
