#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$(echo '0 1 1000000000 um/mod . .'| $FORTH)
printf "%s\n" "$out"
case $out in
    ('18446744073 709551616 ') exit 0;;
esac
exit 2
