#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x begin dup . 1 until ; 99 x')
printf "%s\n" "$out"
case "$out" in
    ("99 ") exit 0;;
esac
exit 2
