#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x BEGIN 1- dup . dup 0= UNTIL ;  4 x .')
printf "%s\n" "$out"
case "$out" in
    ("3 2 1 0 0 ") exit 0;;
esac
exit 2
