#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c 'variable bop 97 bop !
3 bop @ . .')
printf "%s\n" "$out"
case "$out" in
    ("97 3 ") exit 0;;
esac
exit 2
