#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c ': x begin 1- dup . dup while 7 . repeat ; 4 x .')
printf "%s\n" "$out"
case "$out" in
    ("3 7 2 7 1 7 0 0 ") exit 0;;
esac
exit 2
