#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
# Test for bug present on 2016-09-25:
# delimiters preceding a word should be skipped (but they are not).
out=$($FORTH -c '9 1  dup . .')
printf "%s\n" "$out"
case "$out" in
    ("1 1 ") exit 0;;
esac
exit 2
