#!/bin/sh
FORTH=${FORTH:-./64th}
while ! test -x "$FORTH" && [ "$(pwd)" != / ] ; do cd .. ; done
out=$($FORTH -c '
BL WORD  foo COUNT TYPE
')
printf "%s\n" "$out"
case "$out" in
    ("foo") exit 0;;
esac
exit 2
