#!/bin/sh
FORTH=${FORTH:-../../64th}

# This test is non-portable because it assumes that:
# a) we can run «;» in interpret mode; and,
# b) its action is to compile the compilation address of EXIT.

out=$(echo create magic \; magic @ \' exit negate + . | $FORTH | sed 's/ *$//')
echo $out
case $out in
    (0) exit 0;;
esac
exit 2
